language: node_js
node_js:
- stable
install: npm install
services:
- mongodb
script: npm test
after_success: npm run coverage
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: 0ce408b9-df45-410a-8514-80a2dfee1592
  app: ci-test-0001
  on:
    repo: lauriceparkin/mongodb-mongoose-express-ci
  run:
    - "node seed/userProjects.js"