language: node_js
node_js:
- stable
install: npm install
services:
- mongodb
script: npm test
after_success: npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: HerZPqIcUB/phtnB59LicysckR2bj8+Z11XxmC6YCQfCRnta0UtYdZSambkGX2h1WKH+BdTqDWAKEcwnDHM9tuxoeWx6f0KSdDortNxJKuqoBmc9iez5GGXlPHGYsngYfLCYzf2CcvNjMXrV+gi5+k5T87Ao/V3iiuiecKtkqcCgLcKfTI7GKxDqxIsH1T8ixAUXZulJTNJbkZcFtf35557TwuE/CxXG1rsAsmZ0foJvxoRxEdolZRxgJmr6OglL4hqsLOkSKwfdLcydEoehiEo1u9q3Ca+qsx52cL3UPGIkxIx5WRFxpNGtFRuQRno89MKra7Jl37txB4V3+RH1k2SnMdjPDr+rIdpse23c9qwkZnqRpEG5LQUYI9uUk0quo+/V4CCBfx04lqQ50NnjsMzD5TgyxHaycHDwFHLOik0vC9uODH84zhIbSC5l5l8hxB/R4cr0JC4snq8J16pHfVwuSZ4i7xYuwtvKSkldjngHw8mGjh3SkqSvJb1Xk0mJstJVvCsFxMhj9zItlZ39kB5bGjKXXIJXbmoaiIig/p5lccDxmQdMoHMdYtr0JxX1sY6FOvSuYFpZ51S7vracs82tdEBpnmmDIZYA961TZFUyCzDBHxZG0n2fNaZPSbj5E1EGtTpQ69+QHMkb6j1BiqscKGHudO/ueSwJHk627sU=
  app: unit-tests-lab
  on:
    repo: lauriceparkin/mongodb-mongoose-express-ci
  run:
    - "node seed/userProjects.js"